---
- name: Deploy Nginx in Docker
  hosts: nodes
  become: yes
  tasks:
      - name: Pull Nginx docker image
        docker_image:
            name: 'nginx:latest'
            source: pull
            state: present
        vars:
            ansible_python_interpreter: /usr/bin/python3

      - name: Create Docker service for Nginx
        docker_container:
            name: nginx_container
            image: 'nginx:latest'
            state: started
            ports:
                - '80:80'
            volumes:
                - '/vagrant/nginx.conf:/etc/nginx/nginx.conf:ro'
        vars:
            ansible_python_interpreter: /usr/bin/python3
