---
- name: Install Docker on CentOS 7
  hosts: all
  become: true
  tasks:
      - name: Add Docker CE yum repository
        yum_repository:
            name: docker-ce
            description: Docker CE Stable - $basearch
            baseurl: 'https://download.docker.com/linux/centos/7/$basearch/stable'
            gpgcheck: 'yes'
            enabled: 'yes'
            gpgkey: 'https://download.docker.com/linux/centos/gpg'
      - name: Install required packages
        yum:
            name: '{{ packages }}'
            state: present
        vars:
            packages:
                - yum-utils
                - docker-ce
                - docker-ce-cli
                - containerd.io
                - docker-buildx-plugin
                - docker-compose-plugin
                - python3
                - python3-pip
      - name: Start Docker service
        systemd:
            name: docker
            state: started
            enabled: 'yes'
      - name: Install Docker Python library
        pip:
            name: '{{ packages }}'
            executable: pip3
        vars:
            ansible_python_interpreter: /usr/bin/python3
            packages:
                - docker
                - docker-compose
      - name: Pull Nginx docker image
        docker_image:
            name: 'nginx:latest'
            source: pull
            state: present
        vars:
            ansible_python_interpreter: /usr/bin/python3
      - name: Run Nginx docker image
        docker_container:
            name: nginx_container
            image: 'nginx:latest'
            state: started
            ports:
                - '80:80'
            volumes:
                - '/vagrant/nginx.conf:/etc/nginx/nginx.conf:ro'
        vars:
            ansible_python_interpreter: /usr/bin/python3
