---
- name: Install Docker on CentOS 7
  hosts: all
  become: true
  tasks:
      - name: Add Docker CE yum repository
        ansible.builtin.yum_repository:
            name: docker-ce
            description: Docker CE Stable - $basearch
            baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
            gpgcheck: true
            enabled: true
            gpgkey: https://download.docker.com/linux/centos/gpg

      - name: Install required packages
        ansible.builtin.yum:
            name: '{{ packages }}'
            state: present
        vars:
            packages:
                - yum-utils
                - docker-ce
                - docker-ce-cli
                - containerd.io
                - docker-buildx-plugin
                - docker-compose-plugin
                - python3
                - python3-pip

      - name: Start Docker service
        ansible.builtin.systemd:
            name: docker
            state: started
            enabled: true

      - name: Install and upgrade pip
        ansible.builtin.pip:
            name: pip
            extra_args: --upgrade
            executable: pip3
        vars:
            ansible_python_interpreter: /usr/bin/python3

      - name: Install python SDK
        ansible.builtin.pip:
            name: '{{ packages }}'
            executable: pip3
        vars:
            ansible_python_interpreter: /usr/bin/python3
            packages:
                - docker
                - docker-compose

      - name: Add user permissions
        ansible.builtin.shell: 'usermod -aG docker vagrant'
