- name: Install and configure Nginx as a load balancer
  hosts: all
  become: true
  vars:
      nodes:
          - 192.168.50.101
          - 192.168.50.102
          - 192.168.50.103

  tasks:
      - name: Install Nginx
        ansible.builtin.yum:
            name: nginx
            state: present

      - name: Configure Nginx
        ansible.builtin.template:
            src: ../config/nginx.conf.j2
            dest: /etc/nginx/nginx.conf
            owner: root
            group: root
            mode: '0644'
        notify: Restart nginx

      - name: Add firewall rules
        ansible.posix.firewalld:
            permanent: true
            immediate: true
            service: '{{ item }}'
            state: enabled
        with_items:
            - http
            - https

  handlers:
      - name: Restart nginx
        ansible.builtin.service:
            name: nginx
            state: restarted
