---
- name: Install and configure Nginx as a load balancer
  hosts: lb
  become: true
  vars:
      nodes:
          - 192.168.50.101
          - 192.168.50.102
          - 192.168.50.103
  tasks:
      - name: Install Nginx
        yum:
            name: nginx
            state: present

      - name: Configure Nginx
        template:
            src: ../config/nginx.conf.j2
            dest: /etc/nginx/nginx.conf
            owner: root
            group: root
            mode: '0644'
        notify: restart nginx

  handlers:
      - name: restart nginx
        service:
            name: nginx
            state: restarted
